# Rehearsal Director requests
#
# Note This only generates one row per possible rd
# After generation AND the dance_groups are set
#   paste in the dg_ids from the dance_group sheet and set
#   the rd_id column accordingly
#   Then adjust the formulas for the full columns to get the 
#   Lookups working.

name: rd_requests

columns:
  - rd_id
  - rd_name
  - minutes
  - dg_id
  - dg_name
  
protected_rows:
  - 1
  
protected_columns:
  - rd_name
  - dg_name

formulas:
  rd_name: 'VLOOKUP(rd_id,rehearsal_directors!A:D,4,FALSE)'
  dg_name: 'VLOOKUP(dg_id,dance_groups!C:D,2,FALSE)'
  
auto_id_config:
  column: rd_id
  prefix: 'rd_'
  count: 10