# Rehearsal Directors lookup table
# Contains master list of all RDs

name: rehearsal_directors

columns:
  - rd_id
  - first_name
  - last_name
  - full_name
  - email
  - cell

protected_rows:
  - 1

protected_columns:
  - rd_id
  - full_name
  
formulas:
  full_name: 'first_name&" "&last_name'
  
auto_id_config:
  column: rd_id
  prefix: 'rd_'
  count: 10

