# Rehearsal resources
# Normally, this will be 3 rows
# Typically, two of the rows will only get a date change
# A third venue often might change, its start_time and end_time might, as well

name: rehearsal

columns:
  - rehearsal_id
  - venue_id
  - venue_name
  - date
  - weekday
  - start_time
  - end_time

protected_rows:
  - 1

protected_columns:
  - rehearsal_id
  - venue_name
  - weekday

formulas:
  venue_name: 'VLOOKUP(venue_id,venues!A:B,2,FALSE)'
  weekday: 'TEXT(date,"DDDD")'
  # weekday: 'WEEKDAY(date)'

auto_id_config:
  column: rehearsal_id
  prefix: 'rehearsal_'
  count: 4
