# Dances lookup table
# Contains master list of all dances with metadata

name: dances

columns:
  - dance_id
  - name
  - music
  - duration
  - minutes
  - seconds
  - duration_seconds
  - choreo_id

protected_rows:
  - 1

protected_columns:
  - dance_id
  - duration
  - duration_seconds

formulas:
  duration: 'TO_TEXT(minutes)&":"&TEXT(seconds,"00")'
  duration_seconds: '60*minutes+seconds'

auto_id_config:
  column: dance_id
  prefix: 'd_'
  count: 40
