# Dance cast mapping
# Maps which dancers are in which dances

# NOTE - after generation of the sheet
#   Copy the dance_ids from the dances sheet
#   Edit, Paste special, Transpose to populate the other columns


name: dance_cast

columns:
  - dancer_id
  - full_name

protected_columns:
  - dancer_id
  - full_name

formulas:
  full_name: 'VLOOKUP(dance_id,IMPORTRANGE("WORKBOOK_ID","dances!A:B"),2,FALSE)'

auto_id_config:
  column: dancer_id
  prefix: 'dancer_'
  count: 50